library(rtracklayer)
library(GenomicRanges)
library(visnab)
owd <- getwd()
setwd("~/Datas/rda/")
## ucscGenomes()
## session <- browserSession()
## sort(trackNames(session))
## kg <- track(session,'knownGene','hg19',asRangedData=FALSE)
load('hg19kg.rda')
load('hg19rna.rda')
setwd(owd)
visplot(hg19kg,"chr1")

